### ISSUE TITLE
Let Nick know when you want him to read a section

### ISSUE THREAD

**Issue by njtierney** [cpsievert/phd-thesis#5]
Hey Mate!

Let me know if/when you want me to proof read a chapter or section or anything. 

I don't mind if it's super rough and you just need a sanity check, or if you need more close examination of grammar, or spelling, or whatever.

Hope you are going well!

**Comment by cpsievert** [comment]
Hey Nick, sorry for keeping u in the dark. You can download the whole thing here -- https://github.com/cpsievert/phd-thesis/blob/master/docs/bookdown.pdf

Besides the plotly book (chapter 8), you might also find chapter 7 interesting. The overview (chapter 2) might be worth reading too if you're interested in some of the larger picture stuff...

**Comment by njtierney** [comment]
Awesome, I'll get to reading. Looks great!
